echo -e ""
echo -e "Welcome to Sphinx VPS"
echo -e "================================+"
echo -e "List Harga SSH Premium Sphinx"
echo -e "--------------------------------+"
echo -e "- 1 Bulan/30 hari= 10k/Akun" 
echo -e ""
echo -e "- 2 Bulan/60 hari= 15k/Akun"
echo -e ""
echo -e "- 3 Bulan/90 hari= 25k/Akun"
echo -e "--------------------------------+"
echo -e "Selamat Berjualan, Semoga Laris Mhankzz"
echo -e "================================+"
